name: Build and push to GitHub Container Registry

on:
  workflow_call:
    outputs:
      image_digest:
        description: Digest of the build container image
        value: ${{ jobs.build.outputs.image_digest }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_digest: ${{ steps.push.outputs.digest }}

    steps:
      - uses: actions/checkout@v5

      - name: Set variables
        run: |
          echo "date_year=$(date +%Y)" >> $GITHUB_ENV
          echo "date_timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "date_security_expiry_timestamp=$(date -u -d "+6 months" +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Render index.html
        uses: YuKitsune/template-cli@v0.1.1
        with:
          args: --input ./index.html \
            --value "date.year=${{ env.date_year }}" \
            --value "git.ref=${{ github.head_ref || github.ref_name }}" \
            --output . --overwrite
      - name: Render well-knowns
        uses: YuKitsune/template-cli@v0.1.1
        with:
          args: --input ./well-known/sitemap.xml --input ./well-known/security.txt \
            --value "date.timestamp=${{ env.date_timestamp }}" \
            --value "date.security_expiry.timestamp=${{ env.date_security_expiry_timestamp }}" \
            --output ./well-known --overwrite

      # Minify sources
      - name: Minify sources
        uses: docker://devatherock/minify-js:3.1.0
        with:
          add_suffix: false

      # Build ab push docker image
      - uses: docker/setup-buildx-action@v3
      - name: Extract metadata for image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha,prefix=

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
