name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  actions: read
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Set variables
        run: |
          echo "git_shortsha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}:${{ env.git_shortsha }}
          format: spdx-json
          output-file: sbom.spdx.json
          artifact-name: sbom.spdx.json
      - name: Attest SBOM
        uses: actions/attest-sbom@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ needs.build.outputs.image_digest }}
          sbom-path: sbom.spdx.json
          push-to-registry: true
